### ISSUE TITLE
Change all Player behaviour timers into actual Timer nodes

### ISSUE THREAD

**Issue by charasyn** [fheysel/frogGoesToSpace#12]
At the moment, much of the player's behaviour is controlled by timers declared as floating point numbers in the code, which are manually updated each tick. We've decided to change these into actual Timer nodes in the Player scene.

Notes about timers:
- You may not need to use the signal emitted by the timer if you're only trying to check whether the timer has completed or not. In that case I believe it's better to just grab the time_left off of the Timer node and check whether there is time left or if it has completed.
- If your timer is controlling game element logic (ex. player or enemy logic) then please set the timer's Process Mode to Physics instead of the default of idle. This should make it behave more consistently. Only use Process Mode = Idle for animations or sound effects (nothing that could affect anything physics-related).
- If you will always set the timer running by specifying the duration, then don't bother setting it in the scene. We should probably agree to always do this and to define the timer duration as a variable at the top of the file.

Starting timers: `jump_frame_countdown = jump_length` => `$JumpCountdownTimer.start(jump_length)`
Stopping timers: `jump_frame_countdown = 0` => `$JumpCountdownTimer.stop()`
Checking remaining time on the timer: `jump_frame_countdown > 0` => `$JumpCountdownTimer.time_left > 0`
Checking if timer is done or not: $JumpCountdownTimer.is_stopped() : returns a boolean

**Comment by jDenyes** [comment]
Edited timer comments to include is_stopped usability

**Comment by charasyn** [comment]
Closed by #22
